platform :ios, '10.3'

inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

project 'ControlPointDemo'

target 'ControlPointDemo' do
	pod 'Alamofire', '~> 5.0.0.beta.6'
	
	pod 'UPnAtom', :path => '../..'
  pod "GCDWebServer/WebUploader", "~> 3.0"
end
